language: java

cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - openjdk7

install:
  - curl https://raw.githubusercontent.com/cloudius-systems/capstan/master/scripts/download | bash
  - export PATH=$HOME/bin:$PATH

script:
  - capstan build
